name: Deploy

on:
  # Trigger the workflow on push or pull request
  # but only for the main branch --
  push:
    branches:
      - master
  pull_request:
    types: [synchronize]
    branches:
      - master

    # Also trigger on page_build, as well as release created events
  page_build:
    release:
      types: # This configuration does not affect the page_build event above
        - created

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v1

      - name: Removed Old Version
        uses: appleboy/ssh-action@master
        with:
          passphrase: ${{ secrets.DEPLOY_PASSPHRASE }}
          host: ${{ secrets.HOST_DNS }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          script: cd /var/www/html &&
            pm2 stop site &&
            rm -rf vehicles &&
            npm cache clean --force

      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        with:
          #          passphrase: ${{ secrets.DEPLOY_PASSPHRASE }}
          HOST: ${{ secrets.HOST_DNS }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          source: "./"
          target: "/var/www/html/vehicles"

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          passphrase: ${{ secrets.DEPLOY_PASSPHRASE }}
          host: ${{ secrets.HOST_DNS }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          script:
            cd /var/www/html/vehicles &&
            npm install --save --force &&            
            npm run build &&
            cd /var/www/html && pm2 start site